Fix/protractor implementation
htfy96/dollar pull request #2
Opened 2024-03-12 09:17 UTC by SkxPhan

Pull request to fix issue #1.

1. Fix resample function to ensure correct number of points
2. Fix vectorizeStroke function based on Protractor pseudo code paper
3. Fix optimalCosineDistance function
4. Adapt and add test case for the _recognize_ function

2024-03-29 03:17 UTC, htfy96 approved these changes
Sorry for the delay. Checked all proposed changes and they all look great. Thanks for your contribution!

2024-03-29 03:22 UTC, htfy96 requested changes

2024-03-29 03:22 UTC, htfy96 commented on test/test.cpp
> +    CHECK_THAT(score, Catch::Matchers::WithinAbs(17.6808f, 0.001f));
This threshold is too stringent and caused the test to fail in Github CI. Can you change it to `0.01f`?

2024-04-04 00:52 UTC, SkxPhan commented on test/test.cpp
> +    CHECK_THAT(score, Catch::Matchers::WithinAbs(17.6808f, 0.001f));
Done!

2024-04-06 14:07 UTC, htfy96 commented
Hi, the CIs are still failing. Would you like to a look when having time? Alternatively I can also help debugging

2024-04-07 10:35 UTC, SkxPhan commented
HI, I think the first test failed because of the perfect match. Therefore score reach an infinite value due to a zero division happening in the function _recognize_:
```cpp
recognize(const Stroke& target, ItT templateItBegin, ItT templateItEnd)
{
    float maxScore = 0;
    ItT matchedIt = templateItEnd;
    for (ItT templateIt = templateItBegin; templateIt != templateItEnd; ++templateIt) {
        const float d = detail::optimalCosineDistance(target.getVectorizedStroke(), templateIt->getVectorizedStroke());
        const float score = 1.0f / d;
        if (score > maxScore) {
            maxScore = score;
            matchedIt = templateIt;
        }
    }
    return { matchedIt, maxScore };
}

To cope with this specific issue and avoid any undefined behavior, I'll add an if statement to handle the case of d = 0 and modify the test case.

2024-04-09 02:27 UTC, htfy96 approved these changes

2024-04-09 02:27 UTC, merged